server:
  port: 8080
spring:
  application:
    name: chat-app
  data:
    mongodb:
      uri: mongodb+srv://anas2001ks:rinshad3657@cluster0.7v2nsm9.mongodb.net/ChatApp
      auto-index-creation: true
logging:
  level:
    org.springframework.web: INFO
